---
title: "Protein-Ligand binding affinity by DL"
subtitle: "Articles where protein-ligand binding affinity by Deep Learning have been implemented"
categories:
- Deep Learning
toc: false
---
* [2023 PLANET: A Multi-objective Graph Neural Network Model for Protein–Ligand Binding Affinity Prediction](https://doi.org/10.1021/acs.jcim.3c00253){target="_blank"}
* [2023 A Simple Way to Incorporate Target Structural Information in Molecular Generative Models](https://doi.org/10.1021/acs.jcim.3c00293){target="_blank"}
* [2023 Active learning guided drug design lead optimization based on relative binding free energy modeling](https://doi.org/10.26434/chemrxiv-2022-krs1t){target="_blank"}
* [2023 Automated benchmarking of combined protein structure and ligand conformation prediction](https://doi.org/10.22541/au.168382988.85108031/v1){target="_blank"}
* [2023 HAC-Net: A Hybrid Attention-Based Convolutional Neural Network for Highly Accurate Protein–Ligand Binding Affinity Prediction](https://doi.org/10.1021/acs.jcim.3c00251){target="_blank"}
* [2023 Rapid Traversal of Ultralarge Chemical Space using Machine Learning Guided Docking Screens](https://doi.org/10.26434/chemrxiv-2023-w3x36){target="_blank"}
* [2022 Multiphysical graph neural network (MP-GNN) for COVID-19 drug design](https://doi.org/10.1093/bib/bbac231){target="_blank"}
* [2022 DLSSAffinity: protein–ligand binding affinity prediction via a deep learning model](https://doi.org/10.1039/D1CP05558E){target="_blank"}
* [2021 A point cloud-based deep learning strategy for protein–ligand binding affinity prediction](https://doi.org/10.1093/bib/bbab474){target="_blank"}
* [2021 SE-OnionNet: A Convolution Neural Network for Protein–Ligand Binding Affinity Prediction](https://doi.org/10.3389/fgene.2020.607824){target="_blank"}
* [2021 Structure-aware Interactive Graph Neural Networks for the Prediction of Protein-Ligand Binding Affinity](https://doi.org/10.1145/3447548.3467311){target="_blank"}
* [2021 DeepDTAF: a deep learning method to predict protein–ligand binding affinity](https://doi.org/10.1093/bib/bbab072){target="_blank"}
* [2021 Development of a graph convolutional neural network model for efficient prediction of protein-ligand binding affinities](https://doi.org/10.1371/journal.pone.0249404){target="_blank"}
* [2021 DeepAtom: A Framework for Protein-Ligand Binding Affinity Prediction](https://doi.org/10.1109/BIBM47256.2019.8982964){target="_blank"}
* [2021 Persistent spectral–based machine learning (PerSpect ML) for protein-ligand binding affinity prediction](https://doi.org/10.1126/sciadv.abc5329){target="_blank"}
* [2021 Persistent spectral hypergraph based machine learning (PSH-ML) for protein-ligand binding affinity prediction](https://doi.org/10.1093/bib/bbab127){target="_blank"}
* [2021 Improved Protein–Ligand Binding Affinity Prediction with Structure-Based Deep Fusion Inference](https://doi.org/10.1021/acs.jcim.0c01306){target="_blank"}
* [2021 Binding affinity prediction for protein–ligand complex using deep attention mechanism based on intermolecular interactions](https://doi.org/10.1186/s12859-021-04466-0){target="_blank"}
* [2021 Learning protein-ligand binding affinity with atomic environment vectors](https://doi.org/10.1186/s13321-021-00536-w){target="_blank"}
* [2020 AK-Score: Accurate Protein-Ligand Binding Affinity Prediction Using an Ensemble of 3D-Convolutional Neural Networks](https://doi.org/10.3390/ijms21228424){target="_blank"}
* [2020 Binding Affinity Prediction by Pairwise Function Based on Neural Network](https://doi.org/10.1021/acs.jcim.0c00026){target="_blank"}
* [2020 A Deep-Learning View of Chemical Space Designed to Facilitate Drug Discovery](https://doi.org/10.1021/acs.jcim.0c00321){target="_blank"}
* [2020 DockingApp RF: A State-of-the-Art Novel Scoring Function for Molecular Docking in a User-Friendly Interface to AutoDock Vina](https://doi.org/10.3390/ijms21249548){target="_blank"}
* [2019 Development of a protein–ligand extended connectivity (PLEC) fingerprint and its application for binding affinity predictions](https://doi.org/10.1093/bioinformatics/bty757){target="_blank"}
* [2019 AGL-Score: Algebraic Graph Learning Score for Protein–Ligand Binding Scoring, Ranking, Docking, and Screening](https://doi.org/10.1021/acs.jcim.9b00334){target="_blank"}
* [2019 OnionNet: a Multiple-Layer Intermolecular-Contact-Based Convolutional Neural Network for Protein–Ligand Binding Affinity Prediction](https://doi.org/10.1021/acsomega.9b01997){target="_blank"}
* [2018 Representability of algebraic topology for biomolecules in machine learning based scoring and virtual screening](https://doi.org/10.1371/journal.pcbi.1005929){target="_blank"}
* [2018 Development and evaluation of a deep learning model for protein–ligand binding affinity prediction](https://doi.org/10.1093/bioinformatics/bty374){target="_blank"}
* [2018 KDEEP: Protein–Ligand Absolute Binding Affinity Prediction via 3D-Convolutional Neural Networks](https://doi.org/10.1021/acs.jcim.7b00650){target="_blank"}
* [2018 Representability of algebraic topology for biomolecules in machine learning based scoring and virtual screening](https://doi.org/10.1371/journal.pcbi.1005929){target="_blank"}
* [2017 TopologyNet: Topology based deep convolutional and multi-task neural networks for biomolecular property predictions](https://doi.org/10.1371/journal.pcbi.1005690){target="_blank"}




