---
title: "Hinge binders"
subtitle: "Articles about kinase hinge binding molecules"
categories:
- Kinome
toc: false
---

* [Hinge Binders Library](https://enamine.net/compound-libraries/targeted-libraries/kinase-library/hinge-binders-library){target="_blank"}
* [2023 KinaFrag explores the kinase-ligand fragment interaction space for selective kinase inhibitor discovery](https://doi.org/10.1101/2021.03.28.436965){target="_blank"}
* [2022 Designing of kinase hinge binders: A medicinal chemistry perspective](https://doi.org/10.1111/cbdd.14024){target="_blank"}
* [2021 Hinge Binder Scaffold Hopping Identifies Potent Calcium/Calmodulin-Dependent Protein Kinase Kinase 2 (CAMKK2) Inhibitor Chemotypes](https://doi.org/10.1021/acs.jmedchem.0c02274){target="_blank"}
* [2021 KID: A Kinase-Focused Interaction Database and Its Application in the Construction of Kinase-Focused Molecule Databases](https://doi.org/10.1021/acs.jcim.2c00908){target="_blank"}
* [2021 Kinase Inhibitor Scaffold Hopping with Deep Learning Approaches](https://doi.org/10.1021/acs.jcim.1c00608){target="_blank"}
* [2020 In Silico Design and Analysis of a Kinase-Focused Combinatorial Library Considering Diversity and Quality](https://doi.org/10.1021/acs.jcim.9b00841){target="_blank"}
* [2020 Fragment Binding to Kinase Hinge: If Charge Distribution and Local pKa Shifts Mislead Popular Bioisosterism Concepts](https://doi.org/10.1002/anie.202011295){target="_blank"}
* [2019 Discovery of a novel kinase hinge binder fragment by dynamic undocking](https://doi.org/10.1039/C9MD00519F){target="_blank"}
* [2017 Kinase Crystal Miner: A Powerful Approach to Repurposing 3D Hinge Binding Fragments and Its Application to Finding Novel Bruton Tyrosine Kinase Inhibitors](https://doi.org/10.1021/acs.jcim.7b00213){target="_blank"}
* [2015 Kinase hinge binding scaffolds and their hydrogen bond patterns](https://doi.org/10.1016/j.bmc.2015.08.006){target="_blank"}
* [2013 De Novo Design of Protein Kinase Inhibitors by in Silico Identification of Hinge Region-Binding Fragments](https://doi.org/10.1021/cb300729y){target="_blank"}
* [2013 Scaffold mining of kinase hinge binders in crystal structure database](https://doi.org/10.1007/s10822-013-9700-4){target="_blank"}
* [2013 De Novo Design of Protein Kinase Inhibitors by in Silico Identification of Hinge Region-Binding Fragments](https://doi.org/10.1021/cb300729y){target="_blank"}






