---
title: "Ligand pKa calculation"
subtitle: "Articles about pKa calculation for the ligands"
toc: false
categories:
- Protonation
---

* [2023 pK50─A Rigorous Indicator of Individual Functional Group Acidity/Basicity in Multiprotic Compounds](https://doi.org/10.1021/acs.jcim.3c00187){target="_blank"}
* [2023 Epik: pKa and Protonation State Prediction through Machine Learning](https://doi.org/10.1021/acs.jctc.3c00044){target="_blank"}
* [2023 Critical Assessment of pH-Dependent Lipophilic Profiles of Small Molecules for Drug Design: Which One Should We Use and In Which Cases?](https://doi.org/10.26434/chemrxiv-2023-54gv8-v2){target="_blank"}
* [2022 An Accurate Approach for Computational pKa Determination of Phenolic Compounds](https://doi.org/10.3390/molecules27238590){target="_blank"}
* [2022 Machine learning methods for pKa prediction of small molecules: Advances and challenges](https://doi-org.ezproxy.univ-orleans.fr/10.1016/j.drudis.2022.103372){target="_blank"}
* [2022 MF-SuP-pKa: Multi-fidelity modeling with subgraph pooling mechanism for pKa prediction](https://doi.org/10.1016/j.apsb.2022.11.010){target="_blank"}
* [2022 Improving Small Molecule pK a Prediction Using Transfer Learning With Graph Neural Networks](https://doi.org/10.3389%2Ffchem.2022.866585){target="_blank"}
* [2022 Predicting octanol/water partition coefficients and pKa for the SAMPL7 challenge using the SM12, SM8 and SMD solvation models](https://doi.org/10.1007/s10822-022-00474-1){target="_blank"}
* [2021 Evaluation of log P, pKa, and log D predictions from the SAMPL7 blind challenge](https://doi.org/10.1007/s10822-021-00397-3){target="_blank"}
* [2021 MolGpka: A Web Server for Small Molecule pKa Prediction Using a Graph-Convolutional Neural Network](https://doi.org/10.1021/acs.jcim.1c00075){target="_blank"}
* [2021 Overview of the SAMPL6 pKa challenge: evaluating small molecule microscopic and macroscopic pKa predictions](https://doi.org/10.1007/s10822-020-00362-6){target="_blank"}
* [2021 Computer Prediction of pKa Values in Small Molecules and Proteins](https://doi.org/10.1021/acsmedchemlett.1c00435){target="_blank"}
* [2019 Dimorphite-DL: an open-source program for enumerating the ionization states of drug-like small molecules](https://doi.org/10.1186/s13321-019-0336-9){target="_blank"}
* [2019 Rapid and Accurate Prediction of pKa Values of C–H Acids Using Graph Convolutional Neural Networks](https://doi.org/10.1021/jacs.9b05895){target="_blank"}







