---
title: "PROTAC Cell Permeability"
subtitle: "Articles related to PROAC permeability"
toc: false
categories:
- PROTAC
---


* [2023 PROTAC-Induced Glycogen Synthase Kinase 3β Degradation as a Potential Therapeutic Strategy for Alzheimer’s Disease](https://doi.org/10.1021/acschemneuro.3c00096){target="_blank"}
* [2023 Investigating the cell permeability of proteolysis-targeting chimeras (PROTACs)](https://doi.org/10.1080/17460441.2023.2187047){target="_blank"}
* [2023 Physicochemical Property Determinants of Oral Absorption for PROTAC Protein Degraders](https://doi.org/10.1021/acs.jmedchem.3c00740){target="_blank"}
* [2023 Predictive Modeling of PROTAC Cell Permeability with Machine Learning](https://doi.org/10.1021/acsomega.2c07717){target="_blank"}
* [3D Polar Surface Area Calculation](https://pubs.acs.org/doi/suppl/10.1021/acs.jmedchem.8b00347/suppl_file/jm8b00347_si_001.pdf){target="_blank"}
* [2023 Conformational Sampling Deciphers the Chameleonic Properties of a VHL-Based Degrader](https://doi.org/10.3390/pharmaceutics15010272){target="_blank"}
* [2022 Designing Soluble PROTACs: Strategies and Preliminary Guidelines](https://doi.org/10.1021/acs.jmedchem.2c00201){target="_blank"}
* [2022 Linker-Dependent Folding Rationalizes PROTAC Cell Permeability](https://doi.org/10.1021/acs.jmedchem.2c00877){target="_blank"}
* [2022 Direct-to-Biology Accelerates PROTAC Synthesis and the Evaluation of Linker Eﬀects on Permeability and Degradation](https://doi.org/10.1021/acsmedchemlett.2c00124){target="_blank"}
* [2021 Amide-to-Ester Substitution as a Strategy for Optimizing PROTAC Permeability and Cellular Activity](https://doi.org/10.1021/acs.jmedchem.1c01496){target="_blank"}
* [2021 Solution Conformations Shed Light on PROTAC Cell Permeability](https://dx.doi.org/10.1021/acsmedchemlett.0c00556){target="_blank"}
* [2020 Understanding and Improving the Membrane Permeability of VH032-Based PROTACs](https://dx.doi.org/10.1021/acsmedchemlett.0c00265){target="_blank"}






