---
title: "Ultra Large Vitual Screening"
subtitle: "Different articles where Machine Learning and Virtual Screening combined to screen billion of compounds"
toc: false
categories:
- Docking
---

* [2023 Large library docking for novel SARS-CoV-2 main protease non-covalent and covalent inhibitors](https://doi.org/10.1002/pro.4712){target="_blank"}
* [2023 SARS-CoV2 billion-compound docking](https://doi.org/10.1038/s41597-023-01984-9){target="_blank"}
* [2023 AI-accelerated protein-ligand docking for SARS-CoV-2 is 100-fold faster with no significant change in detection](https://doi.org/10.1038/s41598-023-28785-9){target="_blank"}
* [2023 Rapid Traversal of Ultralarge Chemical Space using Machine Learning Guided Docking Screens](https://doi.org/10.26434/chemrxiv-2023-w3x36){target="_blank"}
* [2023 Large-Scale Docking in the Cloud](https://doi.org/10.1021/acs.jcim.3c00031){target="_blank"}
* [2023 The Impact of Supervised Learning Methods in Ultralarge High-Throughput Docking](https://doi.org/10.1021/acs.jcim.2c01471){target="_blank"}
* [2023 Ringtail: A Python Tool for Efficient Management and Storage of Virtual Screening Results](https://doi.org/10.1021/acs.jcim.3c00166){target="_blank"}
* [2023 Uni-Dock: GPU-Accelerated Docking Enables Ultralarge Virtual Screening](https://doi.org/10.1021/acs.jctc.2c01145){target="_blank"}
* [2023 Reducing false positive rate of docking-based virtual screening by active learning](https://doi.org/10.1093/bib/bbac626){target="_blank"}
* [2023 Efficient design of peptide-binding polymers using active learning approaches](https://doi.org/10.1016/j.jconrel.2022.11.023){target="_blank"}
* [2023 Chemical Space Virtual Screening against Hard-to-Drug RNA Methyltransferases DNMT2 and NSUN6](https://doi.org/10.3390/ijms24076109){target="_blank"}
* [2023 AI-Driven Discovery of SARS-CoV-2 Main Protease Fragment-like Inhibitors with Antiviral Activity In Vitro](https://doi.org/10.1021/acs.jcim.3c00409){target="_blank"}
* [2023 Targeting in silico GPCR conformations with ultra-large library screening for hit discovery](https://doi.org/10.1016/j.tips.2022.12.006){target="_blank"}
* [2022 Artificial intelligence–enabled virtual screening of ultra-large chemical libraries with deep docking](https://doi.org/10.1038/s41596-021-00659-2){target="_blank"}
* [2022 Parallel tempered genetic algorithm guided by deep neural networks for inverse molecular design](https://doi.org/10.1039/D2DD00003B){target="_blank"}
* [2022 Docking-based Virtual Screening with Multi-Task Learning](https://doi.org/10.1109/BIBM52615.2021.9669513){target="_blank"}
* [2022 Magnet for the Needle in Haystack: “Crystal Structure First” Fragment Hits Unlock Active Chemical Matter Using Targeted Exploration of Vast Chemical Spaces](https://doi.org/10.1021/acs.jmedchem.2c00813){target="_blank"}
* [2022 Self-Focusing Virtual Screening with Active Design Space Pruning](https://doi.org/10.1021/acs.jcim.2c00554){target="_blank"}
* [2022 Exploration of Ultralarge Compound Collections for Drug Discovery](https://doi.org/10.1021/acs.jcim.2c00224){target="_blank"}
* [2022 Efficient and enhanced sampling of drug‐like chemical space for virtual screening and molecular design using modern machine learning methods](https://doi.org/10.1002/wcms.1637){target="_blank"}
* [2022 Discovery of Kinase and Carbonic Anhydrase Dual Inhibitors by Machine Learning Classification and Experiments](https://doi.org/10.3390/ph15020236){target="_blank"}
* [2022 Vina-FPGA: A Hardware-Accelerated Molecular Docking Tool With Fixed-Point Quantization and Low-Level Parallelism](https://doi.org/10.1109/TVLSI.2022.3217275){target="_blank"}
* [2022 Chemical Space Exploration with Active Learning and Alchemical Free Energies](https://doi.org/10.1021/acs.jctc.2c00752){target="_blank"}
* [2022 Chemical space docking enables large-scale structure-based virtual screening to discover ROCK1 kinase inhibitors](https://doi.org/10.1038/s41467-022-33981-8){target="_blank"}
* [2022 Synthon-based ligand discovery in virtual libraries of over 11 billion compounds](https://doi.org/10.1038/s41586-021-04220-9){target="_blank"}
* [2022 Ultralarge Virtual Screening Identifies SARS-CoV-2 Main Protease Inhibitors with Broad-Spectrum Activity against Coronaviruses](https://doi.org/10.1021/jacs.1c08402){target="_blank"}
* [2021 Efficient Exploration of Chemical Space with Docking and Deep Learning](https://doi.org/10.1021/acs.jctc.1c00810){target="_blank"}
* [2021 Automated discovery of noncovalent inhibitors of SARS-CoV-2 main protease by consensus Deep Docking of 40 billion small molecules](https://doi.org/10.1039/D1SC05579H){target="_blank"}
* [2021 A practical guide to large-scale docking](https://doi.org/10.1038/s41596-021-00597-z){target="_blank"}
* [2021 Accelerating high-throughput virtual screening through molecular pool-based active learning](https://doi.org/10.1039/D0SC06805E){target="_blank"}
* [2021 A multi-pronged approach targeting SARS-CoV-2 proteins using ultra-large virtual screening](https://doi.org/10.1016/){target="_blank"}
* [2020 Deep Docking: A Deep Learning Platform for Augmentation of Structure Based Drug Discovery](https://doi.org/10.1021/acscentsci.0c00229){target="_blank"}
* [2020 Rapid Identification of Potential Inhibitors of SARS-CoV-2 Main Protease by Deep Docking of 1.3 Billion Compounds](https://doi.org/10.1002/minf.202000028){target="_blank"}
* [2020 An open-source drug discovery platform enables ultra-large virtual screens](https://doi.org/10.1038/s41586-020-2117-z){target="_blank"}
* [2019 Ultra-large library docking for discovering new chemotypes](https://doi.org/10.1038/s41586-019-0917-9){target="_blank"}

